### ISSUE TITLE
Error using synthControl.setWarp();

### ISSUE THREAD

**Issue by Aduffy** [paulrosen/abcjs#585]
I am using an external control (slider) to set the BPM using the setWarp() function, but it gets a random error in console and NAN displaying in the player time 

`Uncaught (in promise) Error: MIDI is not supported in this browser.`

Also using a % to set the BPM makes it imposable to set values such as 60 BPM 

synthControl.setWarp(33.99999999999999); will set it to 61
synthControl.setWarp(33.9999999999999); will set it to 59 

Is there a way to set BPM directly ? 
Such as 
synthControl.setBPM(60)

**Comment by paulrosen** [comment]
I'd like to debug that error. Do you have a small example of that error happening?

For the tempo, I'm not sure how you are using it. The simplest way to set it is to add this to your ABC string: `Q: 1/4=60`. You can also pass it in `synthControl.setTune(..., ..., { qpm: 60 })`

**Comment by Aduffy** [comment]
I have a fairly simple ABC string that is a scale. I have a slider so the user can control the speed of playback based on BPM. 

Ill make a minimized version in a code pen and post a link here tomorrow for you.

**Comment by Aduffy** [comment]
Hi Paul I have posted an example of issue at 
https://music.duffield.me/abc2.html

If you could also review and comment on why it is not loading my local soundfont file, that would be greatly appreciated.

**Comment by Aduffy** [comment]
my soundfont loading issues are resolved but the setWarp() errors as well as event syncing errors are still unresolved.

**Comment by paulrosen** [comment]
Yeah, that's an interesting one! It looks like it is timing related. I'll look into it.

**Comment by paulrosen** [comment]
I think the basic problem is that when you call setWarp() it takes a little bit of time to recreate the audio buffer - depending on the music and the computer it might be up to a few seconds. So when you call it repeatedly and quickly the work backs up and the resources get depleted.

In theory you should have been able to do something like (not tested - kind of pseudo code):
```
var isProcessing = false;
var latestValue;

function tempoChange(perc) {
  if (isProcessing) {
    latestValue = perc;
  } else {
    isProcessing = true;
    synthControl.setWarp(perc).then(function () {
      isProcessing = false;
      if (latestValue) {
        perc = latestValue;
        latestValue = undefined;
        tempoChange(perc);
    }
  }).catch (function (error) {
    console.log("error in setWrap: ", error);
  });
}
```
Unfortunately I found a bug where setWarp isn't returning the promise, so the above won't work until version 6.0.0-beta.25. Fortunately, that should be out soon.

**Comment by Aduffy** [comment]
Thanks Paul. I will give this a try as soon as b25 is released. I had also adjusted my slider to only fire my event on end instead of on slide.. that did help by only firing just the one time, but still did get error on occasion .. perhaps due to the promise issue?

**Comment by paulrosen** [comment]
Fixed in version 6.0.0-beta.25

**Comment by Aduffy** [comment]
Hi Paul Im sorry to report that I am still seeing issues with setting BMP and Sync in Beta 25. 

**Issues with sync and tempo after setting Tempo / BPM with built in controls**
Steps to reproduce :

1. Press play - Play back is in sync with events (note changes color) BPM shows as 180.
2. Type in "50" in the % box next to where BPM is shown - changes to 45 BPM instead of 90...
3. Press play - Playback is not out of sync with events


https://music.duffield.me/abc3.html

**Comment by Aduffy** [comment]
Opened as new issue since this is closed. 
https://github.com/paulrosen/abcjs/issues/600
